In [2]:
import numpy as np
import random

a = np.random.random((3,2))

In [3]:
a

array([[0.99632882, 0.20897425],
       [0.88428582, 0.93311163],
       [0.22595337, 0.59454656]])

In [4]:
b = np.linspace(-20,-5,15)

In [5]:
b

array([-20.        , -18.92857143, -17.85714286, -16.78571429,
       -15.71428571, -14.64285714, -13.57142857, -12.5       ,
       -11.42857143, -10.35714286,  -9.28571429,  -8.21428571,
        -7.14285714,  -6.07142857,  -5.        ])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr_obj = np.array([1,2])


In [8]:
print(arr_obj)

[1 2]


In [9]:
ba = arr_obj.reshape(2,1)

In [10]:
print(ba)

[[1]
 [2]]


In [11]:
random_arr = np.arange(16)

In [12]:
random_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
random_arr.reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [14]:
a2 = np.random.random((2,3))

In [15]:
a2.size

6

In [16]:
a2.itemsize

8

In [17]:
a2.dtype = 'int16'

In [18]:
a2.dtype

dtype('int16')

In [19]:
a2.itemsize

2

In [20]:
a2.__dir__

<function ndarray.__dir__()>

In [21]:
dd = a2.astype(np.int64)
print(dd)
dd.size

[[ 23983  22502 -31128  16359  23744 -26823  32485  16317 -13960   5887
  -24208  16352]
 [-13454  19448  11553  16359  13044 -27778 -12318  16356 -14170  21040
   29041  16366]]


24

In [22]:
a2.dtype

dtype('int16')

In [23]:
a2


array([[ 23983,  22502, -31128,  16359,  23744, -26823,  32485,  16317,
        -13960,   5887, -24208,  16352],
       [-13454,  19448,  11553,  16359,  13044, -27778, -12318,  16356,
        -14170,  21040,  29041,  16366]], dtype=int16)

In [24]:
a1 = np.arange(1,11).reshape(5,2)
a3 = np.arange(11,21).reshape(2,5)

In [25]:
np.prod(a1,axis=1)

array([ 2, 12, 30, 56, 90])

In [26]:
a1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
a3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
np.dot(a1,a3)

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]])

In [29]:
a1.shape

(5, 2)

In [30]:
a3.shape

(2, 5)

In [31]:
#scalar operations

a1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [32]:
a1.ndim

2

In [33]:
a2.ndim

2

In [34]:
a1 + a2 

ValueError: operands could not be broadcast together with shapes (5,2) (2,12) 

In [ ]:
np.max(a1)

np.int64(10)

In [ ]:
a1 * 4


array([[ 4,  8],
       [12, 16],
       [20, 24],
       [28, 32],
       [36, 40]])

In [ ]:
a1.dot(a3)

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]])

In [ ]:
np.dot(a1,a3)

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]])

In [35]:
a1


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.hsplit(a1,2)

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])]

In [37]:
np.identity(2,dtype=bool)
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
a = np.zeros((3,100),dtype=int)

In [ ]:
a[1,10] = 99

In [ ]:
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 99,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0

In [ ]:
b = np.ones((3,3,3),dtype=float)

In [ ]:
b[2,2,1] = 999

In [ ]:
b

array([[[  1.,   1.,   1.],
        [  1.,   1.,   1.],
        [  1.,   1.,   1.]],

       [[  1.,   1.,   1.],
        [  1.,   1.,   1.],
        [  1.,   1.,   1.]],

       [[  1.,   1.,   1.],
        [  1.,   1.,   1.],
        [  1., 999.,   1.]]])

In [ ]:
ran = np.random.random((3,3,3))

In [ ]:
ran  =  ran * 10000

In [ ]:
np.ceil(ran)

array([[[9231.,  666., 1490.],
        [3581., 7588., 7610.],
        [5687., 1560., 7080.]],

       [[9282., 6904., 3563.],
        [4264., 4764., 2568.],
        [ 455., 6724., 5821.]],

       [[9767., 7896., 9512.],
        [6812., 8351.,  396.],
        [6104., 4641., 1732.]]])

In [ ]:
ran[::,::,0:1:]

array([[[9230.29263891],
        [3580.6360094 ],
        [5686.84682089]],

       [[9281.46915651],
        [4263.38394185],
        [ 454.37973744]],

       [[9766.27300485],
        [6811.1843532 ],
        [6103.3087825 ]]])

In [ ]:
import numpy as np
q = np.random.randint((1,2,10)).reshape(1,3)
#here we are passing a tuple into the randint function hmmmmm  it consider each element in the tuple and gives a random number from 0 to tjat element -1 number

In [ ]:
q

array([[0, 0, 7]], dtype=int32)

In [ ]:
o = np.random.random((2,2))

In [ ]:
o# whereas in the random function it takes only 1 argument that is the shape if 1d then just the no of elements orelse if 2d give the dimensions in the tuple

array([[0.25252206, 0.76126735],
       [0.92897152, 0.91306154]])

In [40]:
#vertical stacking
l=np.arange(1,11).reshape(2,5)
k=np.arange(11,21).reshape(2,5)

In [46]:
np.hstack((l,k))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [47]:
np.vstack((l,k))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
np.vsplit(l,2)#l here is 2 rows and 5 columns

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

Spliting is just the opposite of stacking (not literally)

in splitting we see in which direction are we moving into the array for splitting

dont think splitting as diving into 2 equal parts, rather it is more of splitting is 2 equal parts 