In [3]:
import numpy as np
import random

a = np.random.random((3,2))

In [4]:
a

array([[0.98342887, 0.92632786],
       [0.25273083, 0.81218323],
       [0.98951173, 0.13982365]])

In [8]:
b = np.linspace(-20,-5,15)

In [9]:
b

array([-20.        , -18.92857143, -17.85714286, -16.78571429,
       -15.71428571, -14.64285714, -13.57142857, -12.5       ,
       -11.42857143, -10.35714286,  -9.28571429,  -8.21428571,
        -7.14285714,  -6.07142857,  -5.        ])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr_obj = np.array([])