In [2]:
import numpy as np
import random

a = np.random.random((3,2))

In [3]:
a

array([[0.30763684, 0.2382386 ],
       [0.44332807, 0.67800457],
       [0.67738301, 0.91894397]])

In [4]:
b = np.linspace(-20,-5,15)

In [5]:
b

array([-20.        , -18.92857143, -17.85714286, -16.78571429,
       -15.71428571, -14.64285714, -13.57142857, -12.5       ,
       -11.42857143, -10.35714286,  -9.28571429,  -8.21428571,
        -7.14285714,  -6.07142857,  -5.        ])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr_obj = np.array([1,2])


In [8]:
print(arr_obj)

[1 2]


In [9]:
ba = arr_obj.reshape(2,1)

In [10]:
print(ba)

[[1]
 [2]]


In [11]:
random_arr = np.arange(16)

In [12]:
random_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
random_arr.reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [14]:
a2 = np.random.random((2,3))

In [15]:
a2.size

6

In [16]:
a2.itemsize

8

In [17]:
a2.dtype = 'int16'

In [18]:
a2.dtype

dtype('int16')

In [19]:
a2.itemsize

2

In [20]:
a2.__dir__

<function ndarray.__dir__()>

In [21]:
dd = a2.astype(np.int64)
print(dd)
dd.size

[[ 29248 -11794  24361  16315 -12404  -3179 -27039  16353  13000 -31337
  -26041  16328]
 [-15594 -24972  31616  16348 -11081 -21618 -29319  16366  -9218   4146
   30183  16346]]


24

In [22]:
a2.dtype

dtype('int16')

In [23]:
a2


array([[ 29248, -11794,  24361,  16315, -12404,  -3179, -27039,  16353,
         13000, -31337, -26041,  16328],
       [-15594, -24972,  31616,  16348, -11081, -21618, -29319,  16366,
         -9218,   4146,  30183,  16346]], dtype=int16)

In [26]:
a1 = np.arange(1,11).reshape(5,2)
a3 = np.arange(11,21).reshape(2,5)

In [29]:
np.prod(a1,axis=1)

array([ 2, 12, 30, 56, 90])

In [41]:
a1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
a3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [34]:
np.dot(a1,a3)

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]])

In [37]:
a1.shape

(5, 2)

In [38]:
a3.shape

(2, 5)

In [43]:
#scalar operations

a1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [44]:
a1.ndim

2

In [45]:
a2.ndim

2

In [46]:
a1 + a2 

ValueError: operands could not be broadcast together with shapes (5,2) (2,12) 

In [58]:
np.max(a1)

np.int64(10)

In [56]:
a1 * 4


array([[ 4,  8],
       [12, 16],
       [20, 24],
       [28, 32],
       [36, 40]])

In [57]:
a1.dot(a3)

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]])

In [59]:
np.dot(a1,a3)

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]])

In [63]:
a1.hsplit(2)

AttributeError: 'numpy.ndarray' object has no attribute 'hsplit'

In [64]:
np.hsplit(a1,2)

[array([[1],
        [3],
        [5],
        [7],
        [9]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])]

In [67]:
np.identity(2,dtype=bool)

array([[ True, False],
       [False,  True]])

In [71]:
a = np.zeros((3,100),dtype=int)

In [73]:
a[1,10] = 99

In [74]:
a

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 99,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0

In [83]:
b = np.ones((3,3,3),dtype=float)

In [85]:
b[2,2,1] = 999

In [86]:
b

array([[[  1.,   1.,   1.],
        [  1.,   1.,   1.],
        [  1.,   1.,   1.]],

       [[  1.,   1.,   1.],
        [  1.,   1.,   1.],
        [  1.,   1.,   1.]],

       [[  1.,   1.,   1.],
        [  1.,   1.,   1.],
        [  1., 999.,   1.]]])

In [88]:
ran = np.random.random((3,3,3))

In [95]:
ran  =  ran * 10000

In [96]:
np.ceil(ran)

array([[[9231.,  666., 1490.],
        [3581., 7588., 7610.],
        [5687., 1560., 7080.]],

       [[9282., 6904., 3563.],
        [4264., 4764., 2568.],
        [ 455., 6724., 5821.]],

       [[9767., 7896., 9512.],
        [6812., 8351.,  396.],
        [6104., 4641., 1732.]]])

In [100]:
ran[::,::,0:1:]

array([[[9230.29263891],
        [3580.6360094 ],
        [5686.84682089]],

       [[9281.46915651],
        [4263.38394185],
        [ 454.37973744]],

       [[9766.27300485],
        [6811.1843532 ],
        [6103.3087825 ]]])

In [47]:
import numpy as np
q = np.random.randint((1,2,10)).reshape(1,3)
#here we are passing a tuple into the randint function hmmmmm  it consider each element in the tuple and gives a random number from 0 to tjat element -1 number

In [46]:
q

array([[0, 0, 7]], dtype=int32)

In [59]:
o = np.random.random((2,2))

In [61]:
o# whereas in the random function it takes only 1 argument that is the shape if 1d then just the no of elements orelse if 2d give the dimensions in the tuple

array([[0.25252206, 0.76126735],
       [0.92897152, 0.91306154]])