In [53]:
#Fancy Indexing 
import numpy as np
a2 = np.random.randint(1,10,24,dtype=np.int8) # randint arguments are start , end , number of elements , type 
a2

array([6, 5, 6, 3, 5, 1, 2, 2, 8, 8, 9, 9, 8, 8, 4, 3, 2, 8, 1, 3, 8, 3,
       5, 3], dtype=int8)

In [54]:
a2 = a2.reshape(4,6)

In [55]:
a2[1:3,[2,5]]

array([[8, 9],
       [4, 8]], dtype=int8)

In [56]:
def fun(*a):
    for i in a:
        print(i)

fun(1,'hello',3,4,5,True,False)



1
hello
3
4
5
True
False


In [57]:
#fancing indexing

a5 = np.arange(10).reshape(2,5)

In [58]:
a5.transpose()
a5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
a5[:,[0,4]]

array([[0, 4],
       [5, 9]])

In [60]:
#boolean indexing
a5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
import pandas as pd

df = pd.read_csv("cars.csv")

In [62]:
df.head()

Car  company
0   corolla   toyota
1       Mx3    mazda
2      camry  toyota
3      prado  toyota
4  fortuner   toyota

In [63]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Car      7 non-null      object
 1   company  7 non-null      object
dtypes: object(2)
memory usage: 244.0+ bytes


In [64]:
a6 = np.array(df)

In [65]:
a6

array([['corolla ', 'toyota'],
       ['Mx3 ', 'mazda'],
       ['camry', 'toyota'],
       ['prado', 'toyota'],
       ['fortuner ', 'toyota'],
       ['hilux', 'toyota'],
       ['nexon', 'tata']], dtype=object)

In [78]:
a6.ndim
a6.shape
a6[:,0]


array(['corolla ', 'Mx3 ', 'camry', 'prado', 'fortuner ', 'hilux',
       'nexon'], dtype=object)

In [67]:
(a6[a6[:,:] == 'toyota'])

array(['toyota', 'toyota', 'toyota', 'toyota', 'toyota'], dtype=object)

In [76]:
(a6[:,:] == 'hilux') #& (a6[:,:] == 'toyota') 
a6[(a6[:,:] == 'hilux')]

array(['hilux'], dtype=object)

In [69]:
try:
    a=1
    b='hi'
    print('Processing the info')
    
except:
    print('hello')

else:
    print(' good successfully completed!')
finally:
    print('"""""""""""ERROR HANDLING EXAMPLE CODE!""""""""""""')
    


Processing the info
 good successfully completed!
"""""""""""ERROR HANDLING EXAMPLE CODE!""""""""""""
