In [1]:
import numpy as np

In [2]:
a=[4,3,5,3,3]
sorted(a)#sorting using this technique will always return a list so wont work for numpy array
a1 = np.random.randint(1,100,20)
np.sort(a1)



array([ 2,  5, 10, 13, 19, 25, 34, 35, 37, 53, 57, 62, 74, 77, 80, 85, 88,
       90, 97, 99], dtype=int32)

In [3]:
a2 =  np.random.random((3,3))
a2*=10
a2 = np.ceil(a2)
np.sort(a2,axis=1)


array([[6., 7., 7.],
       [2., 4., 5.],
       [1., 3., 4.]])

<h1> Appending in Numpy</h1>

In [4]:
np.append(a1,300)

array([ 97,  77,   2,  25,  85,  35,  74,  37,  57,  99,  62,  19,  10,
        53,  13,  88,  34,   5,  90,  80, 300])

In [5]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.append(b,np.ones((3,1)),axis=1)

array([[1., 2., 3., 1.],
       [4., 5., 6., 1.],
       [7., 8., 9., 1.]])

In [7]:
np.zeros((3,3))#important syntax to remember 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Concatenate 


In [8]:
c = np.array([[1 ,2],[3,4]])
d = np.array([[4,3],[2,1]])


In [9]:
np.concatenate((c,d),axis=0) #similar to vstack and hstack

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [10]:
e = np.array([[1,6,3],[2,3,4]])
np.unique(e)

array([1, 2, 3, 4, 6])

In [11]:
e.shape

(2, 3)

In [12]:
np.expand_dims(e,axis=0).shape

(1, 2, 3)

In [13]:
(np.expand_dims(e,axis=1)).shape

(2, 1, 3)

In [14]:
(np.expand_dims(e,axis=1))

array([[[1, 6, 3]],

       [[2, 3, 4]]])

NP.WHERE() find indeces using condition

In [15]:
#np.where(condition,true,false)
w1 = np.random.randint(1,100,20)
np.where(w1)#return indeces

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [16]:
np.where(w1==99,'X',w1)#returns array if other arguments passed

array(['18', '28', '24', '25', '30', '95', '95', '36', '87', '48', '93',
       '48', '12', '44', '41', '16', '79', '47', '62', '93'], dtype='<U11')

In [17]:
np.argmax(w1)#return the index value of biggest value in the array 

np.int64(5)

In [18]:
w1

array([18, 28, 24, 25, 30, 95, 95, 36, 87, 48, 93, 48, 12, 44, 41, 16, 79,
       47, 62, 93], dtype=int32)

In [19]:
a2

array([[7., 7., 6.],
       [5., 2., 4.],
       [3., 4., 1.]])

In [20]:
np.argmax(a2,axis=0)

array([0, 0, 0])

In [21]:
np.argmin(a2,axis=0)

array([2, 1, 2])

In [22]:
a1

array([97, 77,  2, 25, 85, 35, 74, 37, 57, 99, 62, 19, 10, 53, 13, 88, 34,
        5, 90, 80], dtype=int32)

In [23]:
np.cumsum(a1)

array([  97,  174,  176,  201,  286,  321,  395,  432,  489,  588,  650,
        669,  679,  732,  745,  833,  867,  872,  962, 1042])

In [24]:
np.cumprod(a1)

array([                  97,                 7469,                14938,
                     373450,             31743250,           1111013750,
                82215017500,        3041955647500,      173391471907500,
          17165755718842500,  1064276854568235000,  1774516163086913384,
        -701582442840417776,  -290381323123038896, -3774957200599505648,
        -154840325984567936, -5264571083475309824, -7876111343666997504,
       -7873746129066813952, -2710391819220361216])

In [25]:
a2

array([[7., 7., 6.],
       [5., 2., 4.],
       [3., 4., 1.]])

In [26]:
np.percentile(a2,50,axis=0)#the middle argument is the position from which u wanna calculate the percentile

array([5., 4., 4.])

In [30]:
np.histogram(w1,(10,20,30,40,50,60,70,80,90,100))

(array([3, 3, 2, 5, 0, 1, 1, 1, 4]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [28]:
w1

array([18, 28, 24, 25, 30, 95, 95, 36, 87, 48, 93, 48, 12, 44, 41, 16, 79,
       47, 62, 93], dtype=int32)