In [56]:
import numpy as np

In [57]:
a=[4,3,5,3,3]
sorted(a)#sorting using this technique will always return a list so wont work for numpy array
a1 = np.random.randint(1,100,20)
np.sort(a1)



array([ 1,  4,  8,  9,  9, 13, 18, 30, 31, 31, 33, 43, 56, 57, 68, 70, 79,
       90, 95, 95], dtype=int32)

In [58]:
a2 =  np.random.random((3,3))
a2*=10
a2 = np.ceil(a2)
np.sort(a2,axis=1)


array([[2., 4., 8.],
       [2., 5., 9.],
       [2., 7., 8.]])

<h1> Appending in Numpy</h1>

In [59]:
np.append(a1,300)

array([  9,  18,  56,  95,  31,  13,  79,   4,  57,  70,  30,   8,  95,
        31,  68,  33,  90,   1,   9,  43, 300])

In [60]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.append(b,np.ones((3,1)),axis=1)

array([[1., 2., 3., 1.],
       [4., 5., 6., 1.],
       [7., 8., 9., 1.]])

In [62]:
np.zeros((3,3))#important syntax to remember 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Concatenate 


In [63]:
c = np.array([[1 ,2],[3,4]])
d = np.array([[4,3],[2,1]])


In [64]:
np.concatenate((c,d),axis=0) #similar to vstack and hstack

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [65]:
e = np.array([[1,6,3],[2,3,4]])
np.unique(e)

array([1, 2, 3, 4, 6])

In [66]:
e.shape

(2, 3)

In [67]:
np.expand_dims(e,axis=0).shape

(1, 2, 3)

In [68]:
(np.expand_dims(e,axis=1)).shape

(2, 1, 3)

In [69]:
(np.expand_dims(e,axis=1))

array([[[1, 6, 3]],

       [[2, 3, 4]]])

NP.WHERE() find indeces using condition

In [70]:
#np.where(condition,true,false)
w1 = np.random.randint(1,100,20)
np.where(w1)#return indeces

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [71]:
np.where(w1==99,'X',w1)#returns array if other arguments passed

array(['60', '83', '69', '76', '45', '4', '98', '68', '58', '12', '87',
       '1', '9', '19', '82', '49', '44', '57', '54', '49'], dtype='<U11')

In [72]:
np.argmax(w1)#return the index value of biggest value in the array 

np.int64(6)

In [73]:
w1

array([60, 83, 69, 76, 45,  4, 98, 68, 58, 12, 87,  1,  9, 19, 82, 49, 44,
       57, 54, 49], dtype=int32)

In [74]:
a2

array([[4., 2., 8.],
       [5., 2., 9.],
       [7., 8., 2.]])

In [75]:
np.argmax(a2,axis=0)

array([2, 2, 1])

In [76]:
np.argmin(a2,axis=0)

array([0, 0, 2])

In [77]:
a1

array([ 9, 18, 56, 95, 31, 13, 79,  4, 57, 70, 30,  8, 95, 31, 68, 33, 90,
        1,  9, 43], dtype=int32)

In [78]:
np.cumsum(a1)

array([  9,  27,  83, 178, 209, 222, 301, 305, 362, 432, 462, 470, 565,
       596, 664, 697, 787, 788, 797, 840])

In [79]:
np.cumprod(a1)

array([                   9,                  162,                 9072,
                     861840,             26717040,            347321520,
                27438400080,         109753600320,        6255955218240,
            437916865276800,    13137505958304000,   105100047666432000,
       -8462239545398511616, -4075008875420137472,  -399442422926073856,
        5265144117149114368, -5752375373028048896, -5752375373028048896,
        3568853863876214784,  5886763557000822784])

In [80]:
a2

array([[4., 2., 8.],
       [5., 2., 9.],
       [7., 8., 2.]])

In [81]:
np.percentile(a2,50,axis=0)#the middle argument is the position from which u wanna calculate the percentile

array([5., 2., 8.])

In [82]:
np.histogram(w1,(10,20,30,40,50,60,70,80,90,100))

(array([2, 0, 0, 4, 3, 3, 1, 3, 1]),
 array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [83]:
w1

array([60, 83, 69, 76, 45,  4, 98, 68, 58, 12, 87,  1,  9, 19, 82, 49, 44,
       57, 54, 49], dtype=int32)

In [84]:
[np.isin(a,(72,10,3))]

[array([False,  True, False,  True,  True])]

<h2>Tasks</h2>


In [85]:
t1 = np.random.randint(1,100,12).reshape(3,4)
t1

array([[89, 20, 19, 87],
       [95, 75, 33, 15],
       [89, 49, 75, 23]], dtype=int32)

In [86]:
[np.sort(t1,axis=0)[:,1]]

[array([20, 49, 75], dtype=int32)]

<h1>SET RELATED FUNCTIONS</h1>

In [91]:
s1 = np.array([1,2,3,4,5,6])
s2 = np.array([4,5,6,7,8,9])

In [92]:
np.union1d(s1,s2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
s1[np.isin(s1,[3,6])]

array([3, 6])

In [98]:
np.put(s1,[0,1],[34,45])

In [99]:
s1

array([34, 45,  3,  4,  5,  6])

In [100]:
np.intersect1d(s1,s2)

array([4, 5, 6])

In [101]:
np.setxor1d(s1,s2)

array([ 3,  7,  8,  9, 34, 45])

In [102]:
np.setdiff1d(s1,s2)

array([ 3, 34, 45])

In [105]:
np.in1d(s1,[1,3])

C:\Users\faisa\AppData\Local\Temp\ipykernel_12460\3742173368.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(s1,[1,3])


array([False, False,  True, False, False, False])

In [107]:
s1

array([34, 45,  3,  4,  5,  6])

In [108]:
np.clip(s1,a_min=5,a_max=30)

array([30, 30,  5,  5,  5,  6])