In [1]:
import numpy as np

In [12]:
a=[4,3,5,3,3]
sorted(a)#sorting using this technique will always return a list so wont work for numpy array
a1 = np.random.randint(1,100,20)
np.sort(a1)



array([ 7,  9, 15, 16, 21, 22, 23, 29, 32, 44, 52, 56, 61, 66, 79, 83, 87,
       87, 92, 95], dtype=int32)

In [47]:
a2 =  np.random.random((3,3))
a2*=10
a2 = np.ceil(a2)
np.sort(a2,axis=1)


array([[5., 6., 8.],
       [1., 2., 9.],
       [3., 7., 8.]])

<h1> Appending in Numpy</h1>

In [13]:
np.append(a1,300)

array([ 22,   7,  15,  92,  87,  44,  52,  21,  87,  29,  66,  23,  95,
        32,   9,  83,  61,  56,  79,  16, 300])

In [16]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.append(b,np.ones((3,1)),axis=1)

array([[1., 2., 3., 1.],
       [4., 5., 6., 1.],
       [7., 8., 9., 1.]])

In [49]:
np.zeros((3,3))#important syntax to remember 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Concatenate 


In [53]:
c = np.array([[1 ,2],[3,4]])
d = np.array([[4,3],[2,1]])


In [54]:
np.concatenate((c,d),axis=0) #similar to vstack and hstack

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [58]:
e = np.array([[1,6,3],[2,3,4]])
np.unique(e)

array([1, 2, 3, 4, 6])

In [59]:
e.shape

(2, 3)

In [78]:
np.expand_dims(e,axis=0).shape

(1, 2, 3)

In [74]:
(np.expand_dims(e,axis=1)).shape

(2, 1, 3)

In [75]:
(np.expand_dims(e,axis=1))

array([[[1, 6, 3]],

       [[2, 3, 4]]])

NP.WHERE() find indeces using condition

In [86]:
#np.where(condition,true,false)
w1 = np.random.randint(1,100,20)
np.where(w1)#return indeces

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),)

In [92]:
np.where(w1==99,'X',w1)#returns array if other arguments passed

array(['36', '95', '57', '8', '41', '76', '46', '94', '67', '45', '26',
       '98', '6', '88', '90', '43', '76', '77', 'X', '34'], dtype='<U11')

In [93]:
np.argmax(w1)#return the index value of biggest value in the array 

np.int64(18)

In [94]:
w1

array([36, 95, 57,  8, 41, 76, 46, 94, 67, 45, 26, 98,  6, 88, 90, 43, 76,
       77, 99, 34], dtype=int32)

In [99]:
a2

array([[8., 5., 6.],
       [1., 2., 9.],
       [8., 3., 7.]])

In [100]:
np.argmax(a2,axis=0)

array([0, 0, 1])

In [101]:
np.argmin(a2,axis=0)

array([1, 1, 0])

In [102]:
a1

array([22,  7, 15, 92, 87, 44, 52, 21, 87, 29, 66, 23, 95, 32,  9, 83, 61,
       56, 79, 16], dtype=int32)

In [103]:
np.cumsum(a1)

array([ 22,  29,  44, 136, 223, 267, 319, 340, 427, 456, 522, 545, 640,
       672, 681, 764, 825, 881, 960, 976])

In [104]:
np.cumprod(a1)

array([                  22,                  154,                 2310,
                     212520,             18489240,            813526560,
                42303381120,         888371003520,       77288277306240,
           2241360041880960,   147929762764143360,  3402384543575297280,
       -8814861687118687488, -5374412882154725376,  6970516281736126464,
        6703785099102396416,  3102521423636045824,  7720503060232601600,
        1177187325960323072,   388253141655617536])

In [105]:
a2

array([[8., 5., 6.],
       [1., 2., 9.],
       [8., 3., 7.]])

In [112]:
np.percentile(a2,50,axis=0)#the middle argument is the position from which u wanna calculate the percentile

array([8., 3., 7.])